global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: services
    metrics_path: /api/v1/metrics/prometheus
    static_configs:
      - targets:
        - 'fluent-bit:24242'
