{
 "title": "Logging with Fluent",
 "description": "Dashboard for monitoring Fluent* applications",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "FluentBit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fluent-bit input records/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rec/s" }
   ],
   "targets": [
    {
     "expr": "irate(fluentbit_input_records_total[10s])",
     "legendFormat": "{{ pod_name }}, {{ name }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output records/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "rec/s" }
   ],
   "targets": [
    {
     "expr": "irate(fluentbit_output_proc_records_total[10s])",
     "legendFormat": "{{ pod_name }}, {{ name }}"
    }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(fluentbit_input_bytes_total[10s])",
     "legendFormat": "{{ pod_name }}, {{ name }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(fluentbit_output_proc_bytes_total[10s])",
     "legendFormat": "{{ pod_name }}, {{ name }}"
    }
   ]
  },
  {
   "title": "Fluent-bit error/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(fluentbit_output_errors_total[10s])",
     "legendFormat": "{{ pod_name }}, {{ name }}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fluentbit_output_retries_total[10s])",
     "legendFormat": "Retries {{ pod_name }} {{name}}"
    },
    {
     "expr": "irate(fluentbit_output_retries_failed_total[10s])",
     "legendFormat": "Failed {{ pod_name }} {{ name}}"
    }
   ]
  }
 ]
}